 --- #YAML:1.0
 name: Lyrics-Fetcher-LyricWiki
 abstract: Get song lyrics from www.LyricWiki.org
 version: 0.04
 author:
   - David Precious <davidp@preshweb.co.uk>
 license: perl
 distribution_type: module
 requires:
   SOAP::Lite: 0
   perl: 5.008
 build_requires:
   Test: 0
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: hand